flags: {}
packages:
- '.'
- location:
    git: https://github.com/haskoin/secp256k1.git
    commit: 5ee603061b3c1eaf2943e8d2c08e6effe85f38e7
  extra-dep: true
- location:
    git: https://github.com/haskoin/haskoin.git
    commit: 142189161ea51a4b14369179d5e6d334ad3f8206
  extra-dep: true
- location:
    git: https://github.com/plaprade/haskoin-node.git
    commit: 0a4595c470e24fceb23749b58845d83054e8c764
  extra-dep: true
- location:
    git: https://github.com/plaprade/haskoin-wallet.git
    commit: 864eee6395de566812c0a4c47a0a9a2237665f28
  extra-dep: true
extra-deps:
- daemons-0.2.1
- leveldb-haskell-0.6.3
- murmur3-1.0.0
- pbkdf-1.1.1.1
- largeword-1.2.4
resolver: lts-3.4
