flags: {}
packages:
- '.'
- location:
    git: https://github.com/haskoin/haskoin.git
    commit: b71bcfa4701e129b69776e6951fe0bb7c8b26ea3
  extra-dep: true
- location:
    git: https://github.com/haskoin/haskoin-node.git
    commit: bf5fa569ed2f66acd5bff346fa4cd796bdcecfcd
  extra-dep: true
- location:
    git: https://github.com/haskoin/haskoin-wallet.git
    commit: 451272e52f6762fd35f62ad83be6bdfcb672286e
  extra-dep: true
extra-deps:
- daemons-0.2.1
- leveldb-haskell-0.6.3
- murmur3-1.0.0
- pbkdf-1.1.1.1
resolver: lts-3.4
