flags:
    haskoin-wallet:
        mysql: true
packages:
- '.'
- location:
    git: https://github.com/plaprade/haskoin.git
    commit: cffeae123e7480135998788842c2b6a7db37c51e
- location:
    git: https://github.com/plaprade/haskoin-wallet.git
    commit: 075dc53e5a583a446fddd2c22675cbc1682d7986
extra-deps:
- SafeSemaphore-0.10.1
- daemons-0.2.1
- leveldb-haskell-0.6.3
- murmur3-1.0.0
- pbkdf-1.1.1.1
- esqueleto-2.2.7
resolver: lts-2.15
