flags: {}
packages:
- '.'
- location: haskoin
  subdirs:
    - haskoin-core
    - haskoin-node
    - haskoin-wallet
  extra-dep: true
extra-deps:
- concurrent-extra-0.7.0.10
- daemons-0.2.1
- murmur3-1.0.3
- pbkdf-1.1.1.1
- secp256k1-0.4.8
resolver: lts-8.13
