flags:
    haskoin-wallet:
        mysql: true
packages:
- '.'
- location:
    git: https://github.com/haskoin/haskoin.git
    commit: 97034a39f6085e724a413654d39b930370c73ae8
- location:
    git: https://github.com/haskoin/haskoin-node.git
    commit: 0b23c412dd46b37b7f2afd5360c08708b1e62d43
- location:
    git: https://github.com/haskoin/haskoin-wallet.git
    commit: 5cc4ffc1da95c5bb002d9c4e5ff81b5295a360b8
extra-deps:
- SafeSemaphore-0.10.1
- daemons-0.2.1
- leveldb-haskell-0.6.3
- murmur3-1.0.0
- pbkdf-1.1.1.1
- esqueleto-2.2.7
resolver: lts-2.15
