flags:
    haskoin-wallet:
        mysql: true
packages:
- '.'
- location:
    git: https://github.com/haskoin/haskoin.git
    commit: f15dc42720ddc6c928c15dd34fac01f5548fe872
- location:
    git: https://github.com/plaprade/haskoin-node.git
    commit: 9248673526b0a69a51ca0e77ebb614e6cf4ad098
- location:
    git: https://github.com/plaprade/haskoin-wallet.git
    commit: b2ebbb4112dcf6541ee75f58eba104410ec32f7a
extra-deps:
- SafeSemaphore-0.10.1
- daemons-0.2.1
- leveldb-haskell-0.6.3
- murmur3-1.0.0
- pbkdf-1.1.1.1
- esqueleto-2.2.7
resolver: lts-2.15
