static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:127.0.0.1" # * for any host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"

# By default Haskoin Wallet uses $HOME/.hw/<network>/hw.sock
wallet-socket:  "_env:HW_SOCKET:ipc://hw.sock"

keyring-name:          "_env:KEYRING:main"
account-name:          "_env:ACCOUNT:faucet"
use-testnet:           "_env:HW_TESTNET:true"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
  user:     "_env:MYSQL_USER:root"
  password: "_env:MYSQL_PASSWORD:"
  host:     "_env:MYSQL_HOST:localhost"
  port:     "_env:MYSQL_PORT:5432"
  database: "_env:MYSQL_DATABASE:haskoin_faucet"
  poolsize: "_env:MYSQL_POOLSIZE:10"

# analytics: UA-YOURCODE

withdrawal-limit:      "_env:WITHDRAW_LIMIT:100000"
withdrawal-reset-time: "_env:RESET_TIME:0"
minimum-confirmations: "_env:CONFIRMATIONS:0"
transaction-fee:       "_env:FEE:1000"
