static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*"         # * for any host
port:           "_env:PORT:54705"     # 54705hi ;-)
approot:        "_env:APPROOT:"
ip-from-header: "_env:IP_FROM_HEADER:false"

# By default Haskoin Wallet uses $HOME/.hw/<network>/hw.sock
wallet-socket:  "_env:HW_SOCKET:ipc://hw.sock"

keyring-name:          "_env:KEYRING:main"
account-name:          "_env:ACCOUNT:faucet"
use-testnet:           "_env:HW_TESTNET:true"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

# analytics: UA-YOURCODE

withdrawal-limit:      "_env:WITHDRAW_LIMIT:100000"
minimum-confirmations: "_env:CONFIRMATIONS:0"
transaction-fee:       "_env:FEE:1000"
